export const COLORS = {
  BACKGROUND_DARK: '#000',
  BACKGROUND_LIGHT: '#FFFFFF',
  BACKGROUND_RED: '#F75056',

  BACKGROUND_NXTBTN: '#4A4A4A',

  COLOR_DARK: '#000',
  COLOR_LIGHT: '#FFFFFF',
  COLOR_LINK: '#4E9BFF',
  COLOR_NXTBTN: '#C9C9C9',

  COLOR_SUBTITLE: '#D0D0D0',

  ACTIVE_OTPUNDERLINE: '#E0263F',
  INACTIVE_OTPUNDERLINE: '#3A3A3A',

  ICON_ACTIVE: '#F75056',
  ICONS_INACTIVE: '#999',

  COLOR_PLACEHOLDER: '#8A8A8E',
  COLOR_BORDER: '#4A4A4A',

  COLOR_SECONDARY_TEXT: '#B8B8B8',

  // chat list
  COLOR_TEXT_PRIMARY: '#222222',
  COLOR_TEXT_SECONDARY: '#777777',
  COLOR_SEPARATOR: '#F2F2F2',
  COLOR_CARD: '#FFFFFF',

  // chat room
  COLOR_CHAT_MY_MESSAGE: '#F75056',
  COLOR_CHAT_OTHER_MESSAGE: '#F2F2F2',
  COLOR_INPUT_BG: '#F5F5F5',

  PROFILE_CHIP_BACKGROUND: '#FFE5E8',
  PROFILE_BUTTON_BACKGROUND: '#F5F5F5',

  COLOR_TEXT_MUTED: '#444',

  CARD_OVERLAY: 'rgba(0,0,0,0.45)',

  COLOR_WHITE: '#FFFFFF',

  COLOR_TEXT_TERTIARY: '#888',

  SWIPE_NOPE: '#FF3B30',
  SWIPE_LIKE: '#34C759',
};
