export const COLORS = {
  BACKGROUND_DARK: '#000',
  BACKGROUND_LIGHT: '#FFFF',
  BACKGROUND_RED: '#F75056',

  BACKGROUND_NXTBTN: '#4A4A4A',

  COLOR_DARK: '#000',
  COLOR_LIGHT: '#FFFF',
  COLOR_LINK: '#4E9BFF',
  COLOR_NXTBTN: '#C9C9C9',

  COLOR_SUBTITLE: '#D0D0D0',

  ACTIVE_OTPUNDERLINE: '#E0263F',
  INACTIVE_OTPUNDERLINE: '#3A3A3A',

  ICON_ACTIVE : '#F75056',
  ICONS_INACTIVE : '#999',

  COLOR_PLACEHOLDER: '#8A8A8E',
  COLOR_BORDER: '#4A4A4A',

  // Add these
  COLOR_SECONDARY_TEXT: '#B8B8B8',
};