export const ROUTES = {
  LOGIN: 'LOGIN',
  PHONE_NUMBER_SCR: 'PHONE_NUMBER_SCR',
  OTP_SCR: 'OTP_SCR',
  EMAIL_SCR: 'EMAIL_SCR',
  STACK_SCR : 'STACK_SCR',
  BOTTOM_TABS : 'BOTTOM_TABS',
  CHAT_SCR :'CHAT_SCR',
  PROFILE_SCR : 'PROFILE_SCR',
  PROFILEPIC_UPLOAD_SCR : 'PROFILEPIC_UPLOAD_SCR'
} as const;